[project]
name = "pkenya-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rav>=0.1.1",
    "tortoise-orm>=0.25.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
